server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
open:
  api:
    title: ${TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    description: Description
    serverUrl: http://localhost:${server.port}
    serverName: server dev
