server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:a}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

open:
  api:
    title: ${TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    description: Description
    serverUrl: http://localhost:${server.port}
    serverName: server dev
